#This make file is used with Watcom C/C++ 32 Compiler v10.0

#debug = /d2 /w1
#all = debug all
prod = /ort /4r /s /w1

game.exe : game.obj actors.obj gamedef.obj global.obj menues.obj player.obj &
			  premap.obj sector.obj sounds.obj rts.obj  &
                          config.obj animlib.obj
           wlink $(all) @makefile.lnk

# use for NAM
#compileoptions = $(prod) $(debug) -imact -DNAM
# use for WW2.  Note that NAM must also be defined...
#compileoptions = $(prod) $(debug) -imact -DNAM -DWW2
# use for Enhanced Duke v2.00.21.  Note that NAM and WW2 must also be defined...
#compileoptions = $(prod) $(debug) -imact -DEDUKE -DNAM -DWW2
# use for Enhanced Duke v2.00.23.  Note that EDUKE, NAM and WW2 must also be defined...
compileoptions = $(prod) $(debug) -imact -DEDUKE20023 -DEDUKE -DNAM -DWW2

globaldependencies = makefile. duke3d.h global.c

game.obj : game.c $(globaldependencies)
	wcc386 game $(compileoptions)
actors.obj : actors.c $(globaldependencies)
	wcc386 actors $(compileoptions)
gamedef.obj : gamedef.c $(globaldependencies)
	wcc386 gamedef $(compileoptions)
global.obj : global.c $(globaldependencies)
	wcc386 global $(compileoptions)
menues.obj : menues.c $(globaldependencies)
	wcc386 menues $(compileoptions)
player.obj : player.c $(globaldependencies)
	wcc386 player $(compileoptions)
premap.obj : premap.c $(globaldependencies)
	wcc386 premap $(compileoptions)
sector.obj : sector.c $(globaldependencies)
	wcc386 sector $(compileoptions)
sounds.obj : sounds.c $(globaldependencies)
        wcc386 sounds /zu $(compileoptions)
rts.obj : rts.c $(globaldependencies)
	wcc386 rts $(compileoptions)
config.obj : config.c $(globaldependencies)
	wcc386 config $(compileoptions)
animlib.obj : animlib.c $(globaldependencies)
        wcc386 animlib $(compileoptions)

clean: 
	del game.obj actors.obj gamedef.obj global.obj menues.obj player.obj
	del premap.obj sector.obj sounds.obj rts.obj 
    del                       config.obj animlib.obj
