system dos4g
option map
option stack=90k
option u
name game
file game,actors,gamedef,global,menues,player,premap,sector,sounds,rts,config
file engine,cache1d,mmulti,a,animlib
file audio_wf.lib,mact386.lib,butwcd4.lib
